# Generated by Django 4.2.1 on 2023-06-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
